### ISSUE TITLE
Reduce steps install garnet 

### ISSUE THREAD

**Issue by Mardii-D-King** [PalisadoesFoundation/garnet#31]
## Steps to Reduce 
Dockerize Garnet
## Issue Type
Feature
## Detailed Points on Issue
As it is now, for a user to install Garnet they would need to go to the documentation which they would then be greeted with the dependencies and a long list of instructions on how to install Garnet. This is quite a tedious process in having to do for every time a user should install Garnet. 

Also, there might be conflicts on production if developers are using different environment like say an Ubuntu, Mint or Debian machine. In essence what can be accessed on an Ubuntu machine may not be accessible to a Mint or Debian machine and vica versa because of their different required dependencies.

## Conclusion
Garnet should be Dockerized so that it can be easily installed and creates a leveled environment for developers on production. Docker uses a Dockerfile to build a Docker image that would contain all the project code, instillation and dependencies that Garnet would require. This image will also contained the specified build environment for that particular machine be it Ubuntu, Mint, Debian etc.

 So as long as the machine that is installing Garnet has Docker installed, all it needs to do is run the image using **one** command and all the packages and dependencies will be installed automatically.

**Comment by Pr0x1m4** [comment]
In the meanwhile, we can use a demo infoset-ng image I created [Infoset-ng-docker](https://hub.docker.com/r/pr0x1m4/infosetng/)

**Comment by Pr0x1m4** [comment]
In light of removing the data collector portion from garnet, this issue has become irrelevant, Closing
