### ISSUE TITLE
Remove data collector

### ISSUE THREAD

**Issue by Mardii-D-King** [PalisadoesFoundation/garnet#41]
Choose one: bug report

Since garnet has now become a static site then there is no need to have the data collector since it will be used  by infoset.

### Input Code

```js
N/A
```

### Garnet Configuration (etc/config.yaml)

```yaml
{
  your
  - config
  - here
}
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| garnet           |  
| node             | 
| npm              | 
| Operating System |

**Comment by Pr0x1m4** [comment]
Resolved by #44
